#!/usr/bin/env python3
"""
Generate ImplementationPlan/effective_cfs_per_pair.md from data/ingestion_report.json
and pipeline config. Describes which features survive the 40% missingness filter per site pair
(data_ingestion.md §10 action item).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_ingestion_report(path: Path | None = None) -> dict:
    path = path or ROOT / "data" / "ingestion_report.json"
    with open(path) as f:
        return json.load(f)


def load_pipeline_config(path: Path | None = None) -> dict:
    path = path or ROOT / "configs" / "pipeline.yaml"
    if not path.exists():
        return {}
    import yaml
    with open(path) as f:
        return yaml.safe_load(f) or {}


def effective_cfs_for_pair(
    site_a: str,
    site_b: str,
    sites_meta: dict,
    candidate_features: list[str],
    threshold_pct: float,
) -> list[str]:
    """Features that have < threshold_pct missing in both site_a and site_b."""
    out = []
    for col in candidate_features:
        miss_a = sites_meta.get(site_a, {}).get("missing_rates", {}).get(col, 0)
        miss_b = sites_meta.get(site_b, {}).get("missing_rates", {}).get(col, 0)
        if miss_a < threshold_pct and miss_b < threshold_pct:
            out.append(col)
    return out


def main() -> None:
    report = load_ingestion_report()
    pipeline_cfg = load_pipeline_config()
    threshold_pct = float(pipeline_cfg.get("missingness_threshold", 0.40) * 100)

    sites_meta = report.get("sites", {})
    cfs_uci = report.get("cfs_uci_cross_site", [
        "age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak"
    ])
    cfs_kaggle_uci = report.get("cfs_kaggle_uci", ["age", "sex", "sys_bp"])

    uci_sites = [s for s in ("cleveland", "hungary", "switzerland", "va") if s in sites_meta]
    lines = [
        "# Effective CFS per Site Pair",
        "",
        "Which features survive the **40% missingness filter** for cross-site experiments. "
        "Derived from `data/ingestion_report.json` and `configs/pipeline.yaml` "
        "(threshold = " + str(threshold_pct) + "%). Generated by `scripts/generate_effective_cfs_doc.py`.",
        "",
        "## UCI ↔ UCI (cross-site)",
        "",
        "Candidate CFS: " + ", ".join(cfs_uci) + ".",
        "",
        "| Train → Test | Effective features | Count | Dropped (>40% missing in either site) |",
        "|--------------|---------------------|-------|------------------------------------------|",
    ]

    for train in uci_sites:
        for test in uci_sites:
            if train == test:
                continue
            eff = effective_cfs_for_pair(train, test, sites_meta, cfs_uci, threshold_pct)
            dropped = [f for f in cfs_uci if f not in eff]
            dropped_str = ", ".join(dropped) if dropped else "—"
            lines.append(f"| {train} → {test} | {', '.join(eff)} | {len(eff)} | {dropped_str} |")

    lines.extend([
        "",
        "## Kaggle ↔ UCI",
        "",
        "Candidate CFS: " + ", ".join(cfs_kaggle_uci) + ". Kaggle has no missingness in these columns.",
        "",
        "| Train → Test | Effective features | Count | Notes |",
        "|--------------|---------------------|-------|-------|",
    ])

    for train in ["kaggle"] + uci_sites:
        for test in ["kaggle"] + uci_sites:
            if train == test:
                continue
            if (train == "kaggle" and test in uci_sites) or (test == "kaggle" and train in uci_sites):
                eff = effective_cfs_for_pair(train, test, sites_meta, cfs_kaggle_uci, threshold_pct)
                notes = "—"
                if len(eff) < len(cfs_kaggle_uci):
                    notes = "Dropped: " + ", ".join(f for f in cfs_kaggle_uci if f not in eff)
                lines.append(f"| {train} → {test} | {', '.join(eff)} | {len(eff)} | {notes} |")

    lines.extend([
        "",
        "## Summary",
        "",
        "- **Cleveland** has low missingness (ca, thal <2%); pairs involving only Cleveland keep all 10 UCI CFS features.",
        "- **Hungary / VA / Switzerland** have heavy missingness on fbs, restecg, thal, ca, etc.; effective CFS shrinks for pairs involving these sites.",
        "- **Kaggle ↔ UCI** always uses the 3-feature CFS (age, sex, sys_bp); all three survive since sys_bp missingness is <40% at all UCI sites.",
        "",
    ])

    out_path = ROOT / "ImplementationPlan" / "effective_cfs_per_pair.md"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
